---
name: ledfx
version: dev
slug: ledfx
description: A network based LED effect controller with support for advanced real-time audio effects!
url: https://github.com/hassio-addons/addon-ledfx
codenotary: codenotary@frenck.dev
webui: "[PROTO:ssl]://[HOST]:[PORT:80]"
audio: true
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
hassio_api: true
auth_api: true
map:
  - ssl
ports:
  80/tcp: 5333
ports_description:
  80/tcp: Web interface
options:
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  certfile: str
  keyfile: str
  ssl: bool
  leave_front_door_open: bool?
